// e-charge up
// export const eCHargeUpVehicles = [
//   {
//     VEHICLE_ID: "EV001",
//     ODOMETER_START_READING: 5000,
//     SOC_START: 47,
//     SOC_END: 70,
//     AVG_VELOCITY: 40,
//     AC_ON_DURATION: 45,
//     CHARGE_TYPE: "Level 1",
//     DISTANCE: 30,
//     AMBIENT_TEMPERATURE: 25,
//     BATTERY_TEMPERATURE: 28,
//     VEHICLE_NUMBER: "CU01",
//     LOCATION: "Delhi, India",
//     CHARGING_STATUS: "Charging",
//     IOT_DEVICE_DETAILS: {
//       SERIAL_NUMBER: "123456789",
//       ID: "IOT006",
//     },
//     Vehicle_Info: {
//       Charging_Pattern: {
//         Total_Energy_Consumed: "1.83 kWh",
//         Average_SOC: "80%",
//         Connector_Type: "Type 1",
//         Total_Charging_Sessions: 5,
//         Average_Charging_Rate: "0.95 kW",
//       },
//       Usage: {
//         Avg_Daily_km_Driven: "87 km",
//         Temperature_High_Low: "33°C / 22°C",
//         SOC_Range: "20% - 85%",
//         Range_Observed_Max_Min: "110 / 85",
//         Real_Range_Observed: "98 km",
//         Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
//       },
//       Battery_Health: {
//         SoH: "98.95 %",
//         Estimated_Degradation: "1.05 %",
//         Battery_Chemistry: "Li-ion",
//         Monthly_SOH_Data: [
//           95.7,
//           95.7,
//           95.7,
//           95.7,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//         ],
//       },
//       Odometer: "10000 km",
//       Vehicle_Model: "Three Wheeler",
//       Model_Year: "2023",
//       VIN: "ECHARGEUP1234",
//       Battery_Capacity: "4.56 kWh",
//       RUL: "1050 cycles",
//       EOL: "09-09-2029",
//       Connected_On: "2024-04-08T08:20:33.602Z",
//       Data_Points_Collected: "3397",
//       Average_Miles_Driven: [
//         23.6,
//         23.6,
//         23.6,
//         23.6,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//       ],
//       Battery: {
//         // odometer: "Current Cycle Number = 44",
//         odometer: "44",
//         batteryCapacity: "5kWh",
//         vehicleModel: "Battery ID = 1",
//         modelYear: "Use Start Date = 2024-03-01",
//         formFactor: "3W",
//         averageSOC: 74.80836031792758,
//         totalChargingSessions: "2",
//         averageChargingRate: "Moderate",
//         chargingRate: "12.580769230769246A",
//         SoH: "95.7%",
//         estimatedDegradation: "4.3%",
//         batteryChemistry: "LFP",
//         SOCRange: "42%-100%",
//         temperature_High_Low: "20.3°C/17.0°C",
//         estimatedPowerOutput: "1.48 kWh",
//         estimatedCapacityOutput: "96.2 Ah",
//         speed_Max_Average: "12.1 / 30",
//         avgDailyKmDriven: 23.6,
//         estimatedDailyEnergyOutput: "28.4 Ah",
//       },
//     },
//   },
//   {
//     VEHICLE_ID: "EV002",
//     ODOMETER_START_READING: 5000,
//     SOC_START: 47,
//     SOC_END: 70,
//     AVG_VELOCITY: 40,
//     AC_ON_DURATION: 45,
//     CHARGE_TYPE: "Level 1",
//     DISTANCE: 30,
//     AMBIENT_TEMPERATURE: 25,
//     BATTERY_TEMPERATURE: 28,
//     VEHICLE_NUMBER: "CU02",
//     LOCATION: "Delhi, India",
//     CHARGING_STATUS: "Charging",
//     IOT_DEVICE_DETAILS: {
//       SERIAL_NUMBER: "123456789",
//       ID: "IOT006",
//     },
//     Vehicle_Info: {
//       Charging_Pattern: {
//         Total_Energy_Consumed: "7.46 kWh",
//         Average_SOC: "80%",
//         Connector_Type: "Type 1",
//         Total_Charging_Sessions: 5,
//         Average_Charging_Rate: "0.95 kW",
//       },
//       Usage: {
//         Avg_Daily_km_Driven: "87 km",
//         Temperature_High_Low: "33°C / 22°C",
//         SOC_Range: "20% - 85%",
//         Range_Observed_Max_Min: "110 / 85",
//         Real_Range_Observed: "98 km",
//         Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
//       },
//       Battery_Health: {
//         SoH: "98.95 %",
//         Estimated_Degradation: "1.05 %",
//         Battery_Chemistry: "Li-ion",
//         Monthly_SOH_Data: [
//           100,
//           100,
//           100,
//           100,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//         ],
//       },
//       Odometer: "10000 km",
//       Vehicle_Model: "Three Wheeler",
//       Model_Year: "2023",
//       VIN: "ECHARGEUP1234",
//       Battery_Capacity: "4.56 kWh",
//       RUL: "1050 cycles",
//       EOL: "09-09-2029",
//       Connected_On: "2024-04-08T08:20:33.602Z",
//       Data_Points_Collected: "6158",
//       Average_Miles_Driven: [
//         35.8,
//         35.8,
//         35.8,
//         35.8,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//       ],

//       Battery: {
//         // odometer: "Current Cycle Number = 64",
//         odometer: "64",
//         batteryCapacity: "5kWh",
//         vehicleModel: "Battery ID = 2",
//         modelYear: "Use Start Date = 2024-03-01",
//         formFactor: "3W",
//         averageSOC: 69.21321857746021,
//         totalChargingSessions: "2",
//         averageChargingRate: "Moderate",
//         chargingRate: "17.449062500000004A",
//         SoH: "100%",
//         estimatedDegradation: "0%",
//         batteryChemistry: "LFP",
//         SOCRange: "20%-99%",
//         temperature_High_Low: "34.0°C/20.0°C",
//         estimatedPowerOutput: "2.78 kWh",
//         estimatedCapacityOutput: "102.2 Ah",
//         speed_Max_Average: "12.5 / 31",
//         avgDailyKmDriven: 35.8,
//         estimatedDailyEnergyOutput: "54.75 Ah",
//       },
//     },
//   },
//   {
//     VEHICLE_ID: "EV003",
//     ODOMETER_START_READING: 5000,
//     SOC_START: 47,
//     SOC_END: 70,
//     AVG_VELOCITY: 40,
//     AC_ON_DURATION: 45,
//     CHARGE_TYPE: "Level 1",
//     DISTANCE: 30,
//     AMBIENT_TEMPERATURE: 25,
//     BATTERY_TEMPERATURE: 28,
//     VEHICLE_NUMBER: "CU03",
//     LOCATION: "Delhi, India",
//     CHARGING_STATUS: "Charging",
//     IOT_DEVICE_DETAILS: {
//       SERIAL_NUMBER: "123456789",
//       ID: "IOT006",
//     },
//     Vehicle_Info: {
//       Charging_Pattern: {
//         Total_Energy_Consumed: "6.17 kWh",
//         Average_SOC: "80%",
//         Connector_Type: "Type 1",
//         Total_Charging_Sessions: 5,
//         Average_Charging_Rate: "0.95 kW",
//       },
//       Usage: {
//         Avg_Daily_km_Driven: "87 km",
//         Temperature_High_Low: "33°C / 22°C",
//         SOC_Range: "20% - 85%",
//         Range_Observed_Max_Min: "110 / 85",
//         Real_Range_Observed: "98 km",
//         Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
//       },
//       Battery_Health: {
//         SoH: "98.95 %",
//         Estimated_Degradation: "1.05 %",
//         Battery_Chemistry: "Li-ion",
//         Monthly_SOH_Data: [
//           97.6,
//           97.6,
//           97.6,
//           97.6,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//         ],
//       },
//       Odometer: "10000 km",
//       Vehicle_Model: "Three Wheeler",
//       Model_Year: "2023",
//       VIN: "ECHARGEUP1234",
//       Battery_Capacity: "5 kWh",
//       RUL: "1050 cycles",
//       EOL: "09-09-2029",
//       Connected_On: "2024-04-08T08:20:33.602Z",
//       Data_Points_Collected: "4508",
//       Average_Miles_Driven: [
//         31.6,
//         31.6,
//         31.6,
//         31.6,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//       ],
//       Battery: {
//         // Battery_3: {
//         // odometer: "Current Cycle Number = 93",
//         odometer: "93",
//         batteryCapacity: "5kWh",
//         vehicleModel: "Battery ID = 3",
//         modelYear: "Use Start Date = 2024-03-01",
//         formFactor: "3W",
//         averageSOC: 73.12947598253275,
//         totalChargingSessions: "2",
//         averageChargingRate: "Moderate",
//         chargingRate: "17.643061224489806A",
//         SoH: "97.6%",
//         estimatedDegradation: "2.4%",
//         batteryChemistry: "LFP",
//         SOCRange: "38%-99%",
//         temperature_High_Low: "27.0°C/17.0°C",
//         estimatedPowerOutput: "2.47 kWh",
//         estimatedCapacityOutput: "101.4 Ah",
//         speed_Max_Average: "12.4 / 46",
//         avgDailyKmDriven: 31.6,
//         estimatedDailyEnergyOutput: "47.58 Ah",
//       },
//     },
//   },
//   {
//     VEHICLE_ID: "EV004",
//     ODOMETER_START_READING: 5000,
//     SOC_START: 47,
//     SOC_END: 70,
//     AVG_VELOCITY: 40,
//     AC_ON_DURATION: 45,
//     CHARGE_TYPE: "Level 1",
//     DISTANCE: 30,
//     AMBIENT_TEMPERATURE: 25,
//     BATTERY_TEMPERATURE: 28,
//     VEHICLE_NUMBER: "CU04",
//     LOCATION: "Delhi, India",
//     CHARGING_STATUS: "Charging",
//     IOT_DEVICE_DETAILS: {
//       SERIAL_NUMBER: "123456789",
//       ID: "IOT006",
//     },
//     Vehicle_Info: {
//       Charging_Pattern: {
//         Total_Energy_Consumed: "",
//         Average_SOC: "80%",
//         Connector_Type: "Type 1",
//         Total_Charging_Sessions: 5,
//         Average_Charging_Rate: "0.95 kW",
//       },
//       Usage: {
//         Avg_Daily_km_Driven: "87 km",
//         Temperature_High_Low: "33°C / 22°C",
//         SOC_Range: "20% - 85%",
//         Range_Observed_Max_Min: "110 / 85",
//         Real_Range_Observed: "98 km",
//         Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
//       },
//       Battery_Health: {
//         SoH: "98.95 %",
//         Estimated_Degradation: "1.05 %",
//         Battery_Chemistry: "Li-ion",
//         Monthly_SOH_Data: [
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//           null,
//         ],
//       },
//       Odometer: "10000 km",
//       Vehicle_Model: "Three Wheeler",
//       Model_Year: "2023",
//       VIN: "ECHARGEUP1234",
//       Battery_Capacity: "4.56 kWh",
//       RUL: "1050 cycles",
//       EOL: "09-09-2029",
//       Connected_On: "2024-04-08T08:20:33.602Z",
//       Data_Points_Collected: "519",
//       Average_Miles_Driven: [
//         0,
//         0,
//         0,
//         0,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//         null,
//       ],
//       Battery: {
//         // Battery_4: {
//         // odometer: "Current Cycle Number = 14",
//         odometer: "14",
//         batteryCapacity: "5kWh",
//         vehicleModel: "Battery ID = 4",
//         modelYear: "Use Start Date = 2024-03-01",
//         averageSOC: 72.21579961464354,
//         totalChargingSessions: "1",
//         averageChargingRate: "Moderate",
//         chargingRate: "nan A",
//         SoH: null,
//         estimatedDegradation: null,
//         batteryChemistry: "LFP",
//         SOCRange: "70%-74%",
//         temperature_High_Low: "21.0°C/17.3°C",
//         estimatedPowerOutput: "-",
//         estimatedCapacityOutput: "-",
//         speed_Max_Average: "4.0 / 13",
//         avgDailyKmDriven: 0,
//         estimatedDailyEnergyOutput: "-",
//       },
//     },
//   },
// ];

// others and echargeup vehicles
export const otherDemoVehicles = [
  {
    VEHICLE_ID: "TEV001",
    ODOMETER_START_READING: 6000,
    SOC_START: 71,
    SOC_END: 65,
    AVG_VELOCITY: 45,
    AC_ON_DURATION: 60,
    CHARGE_TYPE: "Level 2",
    DISTANCE: 35,
    AMBIENT_TEMPERATURE: 28,
    BATTERY_TEMPERATURE: 30,
    VEHICLE_NUMBER: "KA05 AB 3476",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "789456123",
      ID: "IOT001",
    },
    LOCATION: "Bangalore, India",
    CHARGING_STATUS: "Not charging",
    Vehicle_Info: {
      Odometer: "16000 km",
      Vehicle_Model: "Ather 450X",
      Model_Year: "2021",
      VIN: "ATH45X12345678901",
      Battery_Capacity: "3.7 kWh",
      Charging_Pattern: {
        Total_Energy_Consumed: "15 kW",
        Average_SOC: "82%",
        Connector_Type: "Type 2",
        Total_Charging_Sessions: 6,
        Average_Charging_Rate: "0.70 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "74 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "30% - 90%",
        Range_Observed_Max_Min: "110 km/ 80 km",
        Real_Range_Observed: "90 km",
        Observed_vs_EPA_WLTP_provided: "85 km / 150 km",
      },
      Battery_Health: {
        SoH: "98.84 %",
        Estimated_Degradation: "1.16 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          98.88,
          98.85,
          98.84,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      RUL: "820 cycles",
      EOL: "14-01-2029",
      Connected_On: "2024-03-10",
      Data_Points_Collected: "35",
      Average_Miles_Driven: [
        78,
        65,
        74,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    VEHICLE_ID: "TEV002",
    ODOMETER_START_READING: 5500,
    SOC_START: 83,
    SOC_END: 70,
    AVG_VELOCITY: 40,
    AC_ON_DURATION: 45,
    CHARGE_TYPE: "Level 1",
    DISTANCE: 30,
    AMBIENT_TEMPERATURE: 25,
    BATTERY_TEMPERATURE: 28,
    VEHICLE_NUMBER: "KA05 CM 5638",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "987654321",
      ID: "IOT002",
    },
    LOCATION: "Bangalore, India",
    CHARGING_STATUS: "Charging",
    Vehicle_Info: {
      Odometer: "15500 km",
      Vehicle_Model: "Ather 450X",
      Model_Year: "2021",
      VIN: "ATH45X98765432109",
      Battery_Capacity: "3.7 kWh",
      Charging_Pattern: {
        Total_Energy_Consumed: "12 kW",
        Average_SOC: "85%",
        Connector_Type: "Type 2",
        Total_Charging_Sessions: 5,
        Average_Charging_Rate: "0.70 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "65 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "25% - 80%",
        Range_Observed_Max_Min: "120 km / 97 km",
        Real_Range_Observed: "112 km",
        Observed_vs_EPA_WLTP_provided: "112 km / 150 km",
      },
      Battery_Health: {
        SoH: "97.82 %",
        Estimated_Degradation: "2.18 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          97.88,
          97.85,
          97.82,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      RUL: "950 cycles",
      EOL: "05-08-2027",
      Connected_On: "2024-03-09",
      Data_Points_Collected: "18",
      Average_Miles_Driven: [
        60,
        68,
        65,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    VEHICLE_ID: "TEV003",
    ODOMETER_START_READING: 7000,
    SOC_START: 54,
    SOC_END: 33,
    AVG_VELOCITY: 50,
    AC_ON_DURATION: 55,
    CHARGE_TYPE: "Level 2",
    DISTANCE: 40,
    AMBIENT_TEMPERATURE: 32,
    BATTERY_TEMPERATURE: 35,
    VEHICLE_NUMBER: "KA05 PX 9012",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "456789123",
      ID: "IOT003",
    },
    LOCATION: "Bangalore, India",
    CHARGING_STATUS: "Not charging",
    Vehicle_Info: {
      Odometer: "17000 km",
      Vehicle_Model: "Ather 450X",
      Model_Year: "2021",
      VIN: "ATH45X45678912304",
      Battery_Capacity: "3.7 kWh",
      Charging_Pattern: {
        Total_Energy_Consumed: "11 kW",
        Average_SOC: "78%",
        Connector_Type: "Type 2",
        Total_Charging_Sessions: 4,
        Average_Charging_Rate: "0.70 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "83 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "20% - 85%",
        Range_Observed_Max_Min: "105 km / 89 km",
        Real_Range_Observed: "108 km",
        Observed_vs_EPA_WLTP_provided: "108 km / 150 km",
      },
      Battery_Health: {
        SoH: "99.85 %",
        Estimated_Degradation: "0.15 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          99.88,
          98.85,
          98.85,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      RUL: "640 cycles",
      EOL: "21-10-2028",
      Connected_On: "2024-03-08",
      Data_Points_Collected: "24",
      Average_Miles_Driven: [
        80,
        89,
        83,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    VEHICLE_ID: "TEV004",
    ODOMETER_START_READING: 8000,
    SOC_START: 93,
    SOC_END: 55,
    AVG_VELOCITY: 55,
    AC_ON_DURATION: 60,
    CHARGE_TYPE: "Level 1",
    DISTANCE: 45,
    AMBIENT_TEMPERATURE: 30,
    BATTERY_TEMPERATURE: 32,
    VEHICLE_NUMBER: "KA05 LW 3956",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "369852147",
      ID: "IOT004",
    },
    LOCATION: "Bangalore, India",
    CHARGING_STATUS: "Charging",
    Vehicle_Info: {
      Odometer: "18000 km",
      Vehicle_Model: "Ather 450X",
      Model_Year: "2021",
      VIN: "ATH45X36985214705",
      Battery_Capacity: "3.7 kWh",
      Charging_Pattern: {
        Total_Energy_Consumed: "13 kW",
        Average_SOC: "73%",
        Connector_Type: "Type 2",
        Total_Charging_Sessions: 3,
        Average_Charging_Rate: "0.70 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "77 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "15% - 80%",
        Range_Observed_Max_Min: "105 km / 82 km",
        Real_Range_Observed: "98 km",
        Observed_vs_EPA_WLTP_provided: "98 km / 150km",
      },
      Battery_Health: {
        SoH: "97.81 %",
        Estimated_Degradation: "2.19 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          97.88,
          97.85,
          97.81,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      RUL: "580 cycles",
      EOL: "19-04-2026",
      Connected_On: "2024-03-07",
      Data_Points_Collected: "17",
      Average_Miles_Driven: [
        79,
        74,
        77,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    VEHICLE_ID: "TEV005",
    ODOMETER_START_READING: 5000,
    SOC_START: 47,
    SOC_END: 70,
    AVG_VELOCITY: 40,
    AC_ON_DURATION: 45,
    CHARGE_TYPE: "Level 1",
    DISTANCE: 30,
    AMBIENT_TEMPERATURE: 25,
    BATTERY_TEMPERATURE: 28,
    VEHICLE_NUMBER: "KA05 LM 8472",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "123456789",
      ID: "IOT006",
    },
    LOCATION: "Bangalore, India",
    CHARGING_STATUS: "Charging",
    Vehicle_Info: {
      Odometer: "10000 km",
      Vehicle_Model: "TVS iCube",
      Model_Year: "2023",
      VIN: "ICUBE12345678901",
      Battery_Capacity: "4.56 kWh",
      Charging_Pattern: {
        Total_Energy_Consumed: "16 kW",
        Average_SOC: "80%",
        Connector_Type: "Type 1",
        Total_Charging_Sessions: 5,
        Average_Charging_Rate: "0.95 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "81 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "20% - 85%",
        Range_Observed_Max_Min: "110 km / 85 km",
        Real_Range_Observed: "98 km",
        Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
      },
      Battery_Health: {
        SoH: "99.00 %",
        Estimated_Degradation: "1.00 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          99.15,
          99.04,
          99.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      RUL: "1050 cycles",
      EOL: "09-09-2029",
      Connected_On: "2024-03-15",
      Data_Points_Collected: "30",
      Average_Miles_Driven: [
        88,
        93,
        81,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    VEHICLE_ID: "TEV006",
    ODOMETER_START_READING: 6000,
    SOC_START: 85,
    SOC_END: 65,
    AVG_VELOCITY: 45,
    AC_ON_DURATION: 60,
    CHARGE_TYPE: "Level 2",
    DISTANCE: 35,
    AMBIENT_TEMPERATURE: 28,
    BATTERY_TEMPERATURE: 30,
    VEHICLE_NUMBER: "KA05 NO 9677",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "987654321",
      ID: "IOT007",
    },
    LOCATION: "Bangalore, India",
    CHARGING_STATUS: "Not charging",
    Vehicle_Info: {
      Odometer: "11000 km",
      Vehicle_Model: "TVS iCube",
      Model_Year: "2023",
      VIN: "ICUBE98765432109",
      Battery_Capacity: "4.56 kWh",
      Charging_Pattern: {
        Total_Energy_Consumed: "20.5 kW",
        Average_SOC: "82%",
        Connector_Type: "Type 1",
        Total_Charging_Sessions: 6,
        Average_Charging_Rate: "0.95 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "95 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "30% - 90%",
        Range_Observed_Max_Min: "110 km / 94 km",
        Real_Range_Observed: "105 km",
        Observed_vs_EPA_WLTP_provided: "105 km / 145 km",
      },
      Battery_Health: {
        SoH: "98.82 %",
        Estimated_Degradation: "1.18 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          98.88,
          98.85,
          98.82,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      RUL: "580 cycles",
      EOL: "28-02-2027",
      Connected_On: "2024-03-22",
      Data_Points_Collected: "14",
      Average_Miles_Driven: [
        98,
        90,
        95,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  {
    VEHICLE_ID: "TEV007",
    ODOMETER_START_READING: 7000,
    SOC_START: 74,
    SOC_END: 60,
    AVG_VELOCITY: 50,
    AC_ON_DURATION: 55,
    CHARGE_TYPE: "Level 2",
    DISTANCE: 40,
    AMBIENT_TEMPERATURE: 32,
    BATTERY_TEMPERATURE: 35,
    VEHICLE_NUMBER: "KA05 PQ 9012",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "456789123",
      ID: "IOT008",
    },
    LOCATION: "Bangalore, India",
    CHARGING_STATUS: "Not charging",
    Vehicle_Info: {
      Odometer: "12000 km",
      Vehicle_Model: "TVS iCube",
      Model_Year: "2023",
      VIN: "ICUBE45678912304",
      Battery_Capacity: "4.56 kWh",
      Charging_Pattern: {
        Total_Energy_Consumed: "12.5 kW",
        Average_SOC: "78%",
        Connector_Type: "Type 1",
        Total_Charging_Sessions: 4,
        Average_Charging_Rate: "0.95 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "84 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "20% - 85%",
        Range_Observed_Max_Min: "114 km / 98 km",
        Real_Range_Observed: "108 km",
        Observed_vs_EPA_WLTP_provided: "108 km / 145 km",
      },
      Battery_Health: {
        SoH: "96.71 %",
        Estimated_Degradation: "3.29 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          96.82,
          96.75,
          96.71,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      RUL: "910 cycles",
      EOL: "17-11-2028",
      Connected_On: "2024-03-13",
      Data_Points_Collected: "27",
      Average_Miles_Driven: [
        77,
        63,
        84,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    },
  },
  //echargeup-vehicles below
  {
    VEHICLE_ID: "EV001",
    ODOMETER_START_READING: 5000,
    SOC_START: 47,
    SOC_END: 70,
    AVG_VELOCITY: 40,
    AC_ON_DURATION: 45,
    CHARGE_TYPE: "Level 1",
    DISTANCE: 30,
    AMBIENT_TEMPERATURE: 25,
    BATTERY_TEMPERATURE: 28,
    VEHICLE_NUMBER: "CU01",
    LOCATION: "Delhi, India",
    CHARGING_STATUS: "Charging",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "123456789",
      ID: "IOT006",
    },
    Vehicle_Info: {
      Charging_Pattern: {
        Total_Energy_Consumed: "1.83 kWh",
        Average_SOC: "80%",
        Connector_Type: "Type 1",
        Total_Charging_Sessions: 5,
        Average_Charging_Rate: "0.95 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "87 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "20% - 85%",
        Range_Observed_Max_Min: "110 / 85",
        Real_Range_Observed: "98 km",
        Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
      },
      Battery_Health: {
        SoH: "98.95 %",
        Estimated_Degradation: "1.05 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          95.7,
          95.7,
          95.7,
          95.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      Odometer: "10000 km",
      Vehicle_Model: "Three Wheeler",
      Model_Year: "2023",
      VIN: "ECHARGEUP1234",
      Battery_Capacity: "4.56 kWh",
      RUL: "1050 cycles",
      EOL: "09-09-2029",
      Connected_On: "2024-04-08T08:20:33.602Z",
      Data_Points_Collected: "3397",
      Average_Miles_Driven: [
        23.6,
        23.6,
        23.6,
        23.6,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      Battery: {
        // odometer: "Current Cycle Number = 44",
        odometer: "44",
        batteryCapacity: "5kWh",
        vehicleModel: "Battery ID = 1",
        modelYear: "Use Start Date = 2024-03-01",
        formFactor: "3W",
        averageSOC: 74.80836031792758,
        totalChargingSessions: "2",
        averageChargingRate: "Moderate",
        chargingRate: "12.580769230769246A",
        SoH: "95.7%",
        estimatedDegradation: "4.3%",
        batteryChemistry: "LFP",
        SOCRange: "42%-100%",
        temperature_High_Low: "20.3°C/17.0°C",
        estimatedPowerOutput: "1.48 kWh",
        estimatedCapacityOutput: "96.2 Ah",
        speed_Max_Average: "12.1 / 30",
        avgDailyKmDriven: 23.6,
        estimatedDailyEnergyOutput: "28.4 Ah",
      },
    },
  },
  {
    VEHICLE_ID: "EV002",
    ODOMETER_START_READING: 5000,
    SOC_START: 47,
    SOC_END: 70,
    AVG_VELOCITY: 40,
    AC_ON_DURATION: 45,
    CHARGE_TYPE: "Level 1",
    DISTANCE: 30,
    AMBIENT_TEMPERATURE: 25,
    BATTERY_TEMPERATURE: 28,
    VEHICLE_NUMBER: "CU02",
    LOCATION: "Delhi, India",
    CHARGING_STATUS: "Charging",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "123456789",
      ID: "IOT006",
    },
    Vehicle_Info: {
      Charging_Pattern: {
        Total_Energy_Consumed: "7.46 kWh",
        Average_SOC: "80%",
        Connector_Type: "Type 1",
        Total_Charging_Sessions: 5,
        Average_Charging_Rate: "0.95 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "87 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "20% - 85%",
        Range_Observed_Max_Min: "110 / 85",
        Real_Range_Observed: "98 km",
        Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
      },
      Battery_Health: {
        SoH: "98.95 %",
        Estimated_Degradation: "1.05 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          100,
          100,
          100,
          100,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      Odometer: "10000 km",
      Vehicle_Model: "Three Wheeler",
      Model_Year: "2023",
      VIN: "ECHARGEUP1234",
      Battery_Capacity: "4.56 kWh",
      RUL: "1050 cycles",
      EOL: "09-09-2029",
      Connected_On: "2024-04-08T08:20:33.602Z",
      Data_Points_Collected: "6158",
      Average_Miles_Driven: [
        35.8,
        35.8,
        35.8,
        35.8,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],

      Battery: {
        // odometer: "Current Cycle Number = 64",
        odometer: "64",
        batteryCapacity: "5kWh",
        vehicleModel: "Battery ID = 2",
        modelYear: "Use Start Date = 2024-03-01",
        formFactor: "3W",
        averageSOC: 69.21321857746021,
        totalChargingSessions: "2",
        averageChargingRate: "Moderate",
        chargingRate: "17.449062500000004A",
        SoH: "100%",
        estimatedDegradation: "0%",
        batteryChemistry: "LFP",
        SOCRange: "20%-99%",
        temperature_High_Low: "34.0°C/20.0°C",
        estimatedPowerOutput: "2.78 kWh",
        estimatedCapacityOutput: "102.2 Ah",
        speed_Max_Average: "12.5 / 31",
        avgDailyKmDriven: 35.8,
        estimatedDailyEnergyOutput: "54.75 Ah",
      },
    },
  },
  {
    VEHICLE_ID: "EV003",
    ODOMETER_START_READING: 5000,
    SOC_START: 47,
    SOC_END: 70,
    AVG_VELOCITY: 40,
    AC_ON_DURATION: 45,
    CHARGE_TYPE: "Level 1",
    DISTANCE: 30,
    AMBIENT_TEMPERATURE: 25,
    BATTERY_TEMPERATURE: 28,
    VEHICLE_NUMBER: "CU03",
    LOCATION: "Delhi, India",
    CHARGING_STATUS: "Charging",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "123456789",
      ID: "IOT006",
    },
    Vehicle_Info: {
      Charging_Pattern: {
        Total_Energy_Consumed: "6.17 kWh",
        Average_SOC: "80%",
        Connector_Type: "Type 1",
        Total_Charging_Sessions: 5,
        Average_Charging_Rate: "0.95 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "87 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "20% - 85%",
        Range_Observed_Max_Min: "110 / 85",
        Real_Range_Observed: "98 km",
        Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
      },
      Battery_Health: {
        SoH: "98.95 %",
        Estimated_Degradation: "1.05 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          97.6,
          97.6,
          97.6,
          97.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      Odometer: "10000 km",
      Vehicle_Model: "Three Wheeler",
      Model_Year: "2023",
      VIN: "ECHARGEUP1234",
      Battery_Capacity: "5 kWh",
      RUL: "1050 cycles",
      EOL: "09-09-2029",
      Connected_On: "2024-04-08T08:20:33.602Z",
      Data_Points_Collected: "4508",
      Average_Miles_Driven: [
        31.6,
        31.6,
        31.6,
        31.6,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      Battery: {
        // Battery_3: {
        // odometer: "Current Cycle Number = 93",
        odometer: "93",
        batteryCapacity: "5kWh",
        vehicleModel: "Battery ID = 3",
        modelYear: "Use Start Date = 2024-03-01",
        formFactor: "3W",
        averageSOC: 73.12947598253275,
        totalChargingSessions: "2",
        averageChargingRate: "Moderate",
        chargingRate: "17.643061224489806A",
        SoH: "97.6%",
        estimatedDegradation: "2.4%",
        batteryChemistry: "LFP",
        SOCRange: "38%-99%",
        temperature_High_Low: "27.0°C/17.0°C",
        estimatedPowerOutput: "2.47 kWh",
        estimatedCapacityOutput: "101.4 Ah",
        speed_Max_Average: "12.4 / 46",
        avgDailyKmDriven: 31.6,
        estimatedDailyEnergyOutput: "47.58 Ah",
      },
    },
  },
  {
    VEHICLE_ID: "EV004",
    ODOMETER_START_READING: 5000,
    SOC_START: 47,
    SOC_END: 70,
    AVG_VELOCITY: 40,
    AC_ON_DURATION: 45,
    CHARGE_TYPE: "Level 1",
    DISTANCE: 30,
    AMBIENT_TEMPERATURE: 25,
    BATTERY_TEMPERATURE: 28,
    VEHICLE_NUMBER: "CU04",
    LOCATION: "Delhi, India",
    CHARGING_STATUS: "Charging",
    IOT_DEVICE_DETAILS: {
      SERIAL_NUMBER: "123456789",
      ID: "IOT006",
    },
    Vehicle_Info: {
      Charging_Pattern: {
        Total_Energy_Consumed: "",
        Average_SOC: "80%",
        Connector_Type: "Type 1",
        Total_Charging_Sessions: 5,
        Average_Charging_Rate: "0.95 kW",
      },
      Usage: {
        Avg_Daily_km_Driven: "87 km",
        Temperature_High_Low: "33°C / 22°C",
        SOC_Range: "20% - 85%",
        Range_Observed_Max_Min: "110 / 85",
        Real_Range_Observed: "98 km",
        Observed_vs_EPA_WLTP_provided: "98 km / 145 km",
      },
      Battery_Health: {
        SoH: "98.95 %",
        Estimated_Degradation: "1.05 %",
        Battery_Chemistry: "Li-ion",
        Monthly_SOH_Data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
      Odometer: "10000 km",
      Vehicle_Model: "Three Wheeler",
      Model_Year: "2023",
      VIN: "ECHARGEUP1234",
      Battery_Capacity: "4.56 kWh",
      RUL: "1050 cycles",
      EOL: "09-09-2029",
      Connected_On: "2024-04-08T08:20:33.602Z",
      Data_Points_Collected: "519",
      Average_Miles_Driven: [
        0,
        0,
        0,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      Battery: {
        // Battery_4: {
        // odometer: "Current Cycle Number = 14",
        odometer: "14",
        batteryCapacity: "5kWh",
        vehicleModel: "Battery ID = 4",
        modelYear: "Use Start Date = 2024-03-01",
        averageSOC: 72.21579961464354,
        totalChargingSessions: "1",
        averageChargingRate: "Moderate",
        chargingRate: "nan A",
        SoH: null,
        estimatedDegradation: null,
        batteryChemistry: "LFP",
        SOCRange: "70%-74%",
        temperature_High_Low: "21.0°C/17.3°C",
        estimatedPowerOutput: "-",
        estimatedCapacityOutput: "-",
        speed_Max_Average: "4.0 / 13",
        avgDailyKmDriven: 0,
        estimatedDailyEnergyOutput: "-",
      },
    },
  },
];
